---
language: php 

script:
  - phpunit
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

before_install:
  - composer self-update
  - cd project

install:
  - composer install

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly
