---
language: php 

script:
  - phpunit
  - mkdir logs
  - phpunit --coverage-clover logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

before_install:
  - composer self-update

install:
  - composer install

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly
